POST http://localhost:3001/api/order HTTP/1.1
content-type: application/json

{
  "name": "Sample Order Test",
  "phone": "1234567891",
  "deliveryType": "Express",
  "paymentType": "Credit Card",
  "statusId": 2
}

#####

POST http://localhost:3001/api/order HTTP/1.1
content-type: application/json

{
  "name": "Sample Order",
  "phone": "1234567891",
  "deliveryType": "Express",
  "paymentType": "Credit Card",
  "$connect": {
    "products": [
        {
            "productId": 1,
            "quantity": 1
        },
        {
            "productId": 4,
            "quantity": 5
        }
    ]
  }
}

#####

@target = 2

PUT http://localhost:3001/api/order/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "Updated Order",
  "$connect": {
    "products": [
        {
            "productId": 6,
            "quantity": 1,
            "observations": "Faz com amor, por favor"
        },
        {
            "productId": 7,
            "quantity": 5,
            "observations": "BEBA AGUA"
        }
    ]
  }
}

#####

PUT http://localhost:3001/api/order/{{target}} HTTP/1.1
content-type: application/json

{
    "statusId": 3
}


#####

PUT http://localhost:3001/api/order/{{target}} HTTP/1.1
content-type: application/json

{
    "canceled": false
}

#####

DELETE http://localhost:3001/api/order/{{target}} HTTP/1.1
content-type: application/json

#####

GET http://localhost:3001/api/order?filters={"canceled": false} HTTP/1.1
content-type: application/json

#####

GET http://localhost:3001/api/order/{{target}} HTTP/1.1
content-type: application/json
