POST http://localhost:3001/api/product HTTP/1.1
content-type: application/json

{
  "name": "Agua",
  "description": "AGUA!",
  "price": 100.50,
  "categoryId": 4,
  "imgLink": "https://kimpaes.com.br/wp-content/uploads/2020/01/p%C3%A3o-de-hamburguer.png"
}

#####

@target = 2

PUT http://localhost:3001/api/product/{{target}} HTTP/1.1
content-type: application/json

{
  "name": "Updated Product",
  "categoryId": 2
}

#####

DELETE http://localhost:3001/api/product/{{target}} HTTP/1.1
content-type: application/json

#####

GET http://localhost:3001/api/product HTTP/1.1
content-type: application/json

#####

GET http://localhost:3001/api/product/{{target}} HTTP/1.1
content-type: application/json
